#!/bin/bash

if [ $# -ne 1 ]
then
	echo "Usage: ./stop chain-name"
	echo "1st arugment, chain-name: base or optimism"
	exit 1
fi

if ! [[ "$1" == "base" || "$1" == "optimism" ]]
then
	echo "Given chain name ${1} is invalid. Valid chain name is base or optimism"
	exit 1
fi

cmd=`tmux ls`

if [ $? -eq 127 ]
then
	echo "tmux is not installed. Please install and then run"
	exit 1
fi

echo "Stoping ${1}"

stop_script=""

if [ "$1" == "base" ]
then
	stop_script="./stop_base.py"
else
	stop_script="./stop_optimism.py"
fi

dir=`dirname $0`

tmux new-session -d -s stop-l2 "cd $dir && python3 ${stop_script}"

echo "The stopping of ${1} is running in tmux"
echo "Use the command 'tmux a -t stop-l2' to open tmux shell"
